Fix pipelines being split in multiple subgraphs
bakdata/streams-explorer pull request #107
Opened 2021-06-01 11:23 UTC by disrupted

2021-06-01 11:46 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        self.independent_graphs: Dict[str, nx.DiGraph] = {}
rename to `pipelines`

2021-06-01 12:49 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +                graph = existing_graph.copy()
Why do you have to copy the graph?

2021-06-01 13:00 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +                graph = existing_graph.copy()
It couldn't be modified because the graph object is frozen. 

From the docs: 

> To “unfreeze” a graph you must make a copy by creating a new graph object
https://networkx.org/documentation/stable/reference/generated/networkx.classes.function.freeze.html#networkx.classes.function.freeze

2021-06-08 15:33 UTC, philipp94831 requested changes
Please add more test cases, especially wrt connectors and extra input topics

2021-06-08 17:43 UTC, philipp94831 requested changes

2021-06-08 17:43 UTC, philipp94831 commented on backend/tests/test_dataflow_graph.py
> +        assert "output-topic" in pipeline1.nodes
please assert for all expected nodes

2021-06-08 17:43 UTC, philipp94831 commented on backend/tests/test_dataflow_graph.py
> +        df.add_sink(Sink("test-sink", "output-topic"))
Is that the same thing as a KafkaConnector with type Sink?

2021-06-09 07:20 UTC, VictorKuenstler requested changes

2021-06-09 07:20 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +    def assign_pipeline(self, node_name: str) -> Optional[str]:
This does not return anything, right?

2021-06-09 07:20 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        pipeline = app.attributes.get("pipeline")
Please add a method to the k8sApp to get the pipeline and add a constant for the attribute name

2021-06-09 07:41 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +    def assign_pipeline(self, node_name: str) -> Optional[str]:
Yep, I changed it and forgot to update its signature, thanks

2021-06-09 07:43 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        pipeline = app.attributes.get("pipeline")
I already added it, this one has the advantage that it also works for the mocked K8sApp's in our tests

2021-06-09 07:46 UTC, disrupted commented on backend/tests/test_dataflow_graph.py
> +        df.add_sink(Sink("test-sink", "output-topic"))
this is what an extractor plugin for a sink connector would add

2021-06-09 07:49 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        pipeline = app.attributes.get("pipeline")
Ok, then add a constant for the pipeline name, please.

2021-06-09 07:57 UTC, philipp94831 commented on backend/tests/test_dataflow_graph.py
> +        df.add_sink(Sink("test-sink", "output-topic"))
Ok, I just wondered because it looks a bit inconsistent with the source connector. sth we should fix in the future

2021-06-09 08:14 UTC, disrupted commented on backend/tests/test_dataflow_graph.py
> +        df.add_sink(Sink("test-sink", "output-topic"))
yeah, the source connector doesn't add any sources by itself

2021-06-09 12:13 UTC, VictorKuenstler approved these changes

2021-06-09 13:24 UTC, merged