Fix topic info when schema is unavailable
bakdata/streams-explorer pull request #112
Opened 2021-06-09 10:04 UTC by disrupted

Fixes #111

2021-06-10 05:53 UTC, philipp94831 requested changes

2021-06-10 05:53 UTC, philipp94831 commented on backend/streams_explorer/core/services/schemaregistry.py
> +    def get_topic_value_schema_versions(topic: str) -> list:
was the typing beforehand wrong?

2021-06-10 05:53 UTC, philipp94831 commented on backend/tests/test_streams_explorer.py
> +            info=[],
can you also add a test please where this is not empty?

2021-06-15 07:16 UTC, disrupted commented on backend/streams_explorer/core/services/schemaregistry.py
> +    def get_topic_value_schema_versions(topic: str) -> list:
yes

2021-06-15 07:53 UTC, disrupted commented on backend/tests/test_streams_explorer.py
> +            info=[],
I have added it now

2021-06-15 08:33 UTC, philipp94831 commented on backend/tests/test_streams_explorer.py
> +            info=[],
Why did you delete the old one though? It is always good to cover all cases

2021-06-15 08:45 UTC, disrupted commented on backend/tests/test_streams_explorer.py
> +            info=[],
I'd say it's kinda non-standard behaviour for how we use the `LinkingService` but I have added clearing the nodeinfo and the empty check to the test now

2021-06-15 08:52 UTC, philipp94831 approved these changes

2021-06-15 08:57 UTC, merged