Set up link to AKHQ for consumer group
bakdata/streams-explorer pull request #117
Opened 2021-06-16 10:41 UTC by disrupted

Closes #108

2021-06-16 15:33 UTC, philipp94831 requested changes

2021-06-16 15:33 UTC, philipp94831 commented on backend/streams_explorer/defaultlinker.py
> +                return f"{settings.akhq.url}/ui/{settings.akhq.cluster}/group/connect-{connector_name}"
Probably worth to create a variable for the consumer group name because you also use it two lines above

2021-06-16 15:33 UTC, philipp94831 commented on backend/streams_explorer/defaultlinker.py
> +                return f"{settings.akhq.url}/ui/{settings.akhq.cluster}/group/connect-{connector_name}"
What about a test?

2021-06-18 06:08 UTC, VictorKuenstler requested changes

2021-06-18 06:08 UTC, VictorKuenstler commented on frontend/src/api/fetchers.tsx
> +const encodingTagFactory =
Why did the formatting change? I think this should not change by adding a new link.

2021-06-22 10:04 UTC, disrupted commented on frontend/src/api/fetchers.tsx
> +const encodingTagFactory =
this is due to the updated Prettier version (https://github.com/bakdata/streams-explorer/pull/117/commits/019e5c804338253844c47319f2b8d1e7d8acdc79)

2021-06-22 10:04 UTC, disrupted commented on backend/streams_explorer/defaultlinker.py
> +                return f"{settings.akhq.url}/ui/{settings.akhq.cluster}/group/connect-{connector_name}"
added

2021-06-22 11:37 UTC, philipp94831 approved these changes

2021-06-22 12:24 UTC, VictorKuenstler approved these changes

2021-06-22 13:02 UTC, merged