Improve error handling
bakdata/streams-explorer pull request #120
Opened 2021-06-23 15:48 UTC by disrupted

- Raise a 404 if pipeline doesnt exist
- Show descriptive error message in frontend
- Redirect to all pipelines if specific pipeline doesn't exist

2021-07-06 13:28 UTC, philipp94831 commented on frontend/src/App.tsx
> +        setCurrentPipeline(ALL_PIPELINES);
What about the idea to refresh the pipelines/graph once and check if a pipeline with that name was created in the meantime?

2021-07-06 14:00 UTC, philipp94831 commented on frontend/src/App.tsx
> +        setCurrentPipeline(ALL_PIPELINES);
The URL would also need to be updated here, there is still the pipeline parameter

2021-07-06 14:06 UTC, VictorKuenstler requested changes

2021-07-06 14:06 UTC, VictorKuenstler commented on frontend/src/App.tsx
> +    if (graphError) {
Currently, the parameter for a not existing pipeline is kept. I think the parameter should be removed if the pipelines does not exist.

2021-07-06 14:07 UTC, VictorKuenstler commented on frontend/src/App.tsx
> +    if (graphError) {
Duplicate of https://github.com/bakdata/streams-explorer/pull/120#discussion_r664583388

2021-07-06 14:09 UTC, VictorKuenstler commented
This could also close #131 , right? :)

2021-07-06 15:22 UTC, disrupted commented on frontend/src/App.tsx
> +        setCurrentPipeline(ALL_PIPELINES);
> This could also close #131 , right? :)

yep, it does. forgot to mention it here

2021-07-06 15:22 UTC, disrupted commented
> This could also close #131 , right? :)

yep, it does. forgot to mention it here

2021-07-06 15:23 UTC, disrupted commented on frontend/src/App.tsx
> +        setCurrentPipeline(ALL_PIPELINES);
it's a bit tricky but I think I got it now

2021-07-07 06:53 UTC, VictorKuenstler commented on backend/streams_explorer/api/routes/graph.py
> +        if not pipeline_graph:
```suggestion
        if pipeline_graph is None:
```

2021-07-07 09:06 UTC, disrupted commented on frontend/src/App.tsx
> +        setCurrentPipeline(ALL_PIPELINES);
> The URL would also need to be updated here, there is still the pipeline parameter

please see https://github.com/bakdata/streams-explorer/pull/120#discussion_r664658253

2021-07-07 09:17 UTC, VictorKuenstler commented on frontend/src/App.tsx
> +            redirectAllPipelines();
I think, when the cluster was updated just at that moment, the URL parameter should be removed. Otherwise, we would describe a different state in the URL than the actual state in the UI application.

2021-07-07 09:20 UTC, philipp94831 commented on frontend/src/App.tsx
> +        const hideMessage = message.warning("Scraping cluster", 0);
"Refreshing pipelines" seems more appropriate

2021-07-07 09:31 UTC, VictorKuenstler commented on frontend/src/App.tsx
> +        const hideMessage = message.warning("Scraping cluster", 0);
Or "Updating graphs" to be consistent with the other button. Otherwise, I think renaming the other button to "Refresh pipelines" could be more appropriate/understandable than "Update graphs". What do you think?

2021-07-07 09:53 UTC, philipp94831 commented on frontend/src/App.tsx
> +        const hideMessage = message.warning("Scraping cluster", 0);
Although in the backend, the method executed is the same, I think the two different labels make sense because you once want to refresh the available pipelines and the other time want the graphs to change. but I don't mind aligning them

2021-07-07 10:08 UTC, philipp94831 approved these changes

2021-07-07 10:15 UTC, VictorKuenstler approved these changes

2021-07-07 10:16 UTC, merged