Add support for Kowl
bakdata/streams-explorer pull request #124
Opened 2021-06-30 10:44 UTC by disrupted

Closes #122

2021-06-30 15:53 UTC, philipp94831 requested changes

2021-06-30 15:53 UTC, philipp94831 commented on backend/settings.yaml
> +  enable: true
I think false would actually be best, what do you think @VictorKuenstler ?

2021-06-30 15:53 UTC, philipp94831 commented on backend/streams_explorer/defaultlinker.py
> +                NodeInfoListItem(
please extract a method as this is almost the same as for akhq

2021-06-30 15:53 UTC, philipp94831 commented on backend/streams_explorer/defaultlinker.py
> +            kowl_consumer_link = NodeInfoListItem(
see above

2021-07-01 05:47 UTC, philipp94831 commented on backend/streams_explorer/defaultlinker.py
> +    def add_provider(self, name: str):
please find an a bit more specific method name. Think: provider of *what*?

2021-07-01 06:45 UTC, VictorKuenstler commented on backend/settings.yaml
> +  enable: true
Yes, I like that, then you have to configure the message viewer.

2021-07-01 06:52 UTC, VictorKuenstler requested changes

2021-07-01 06:52 UTC, VictorKuenstler commented on backend/settings.yaml
> +kowl:
Please add a comment, which describes that only either akhq or kowl is supported. Maybe you could even bundle both or the whole linking service configuration into one yaml record:
```yaml
linking:
  message_viewer:
    akhq:
      enable: true
     ...
    kowl:
      enable: false
  ...
  monitoring:
  ...
  logging:
  ...
```
Could also be a separate Issue and PR. Also related to: https://github.com/bakdata/streams-explorer/issues/125
What do you think?

2021-07-01 07:03 UTC, philipp94831 commented on backend/settings.yaml
> +kowl:
Let's restructure the configuration in a later stage along with changes to the helm chart (#123)

2021-07-01 08:03 UTC, disrupted commented on backend/settings.yaml
> +kowl:
I agree, also I thought that going forward we could actually allow both integrations to be enabled at the same time, we would just need to differentiate it better in the frontend. Adding the service name there would make it clearer imo

2021-07-01 08:06 UTC, philipp94831 commented on README.md
> +- `akhq.enable` Enable AKHQ (bool, **required**, default: `true`)
update

2021-07-01 08:07 UTC, disrupted commented on README.md
> +- `akhq.enable` Enable AKHQ (bool, **required**, default: `true`)
touché :D

2021-07-01 08:09 UTC, philipp94831 approved these changes

2021-07-01 09:05 UTC, merged