Add support for schema versions
bakdata/streams-explorer pull request #157
Opened 2021-08-18 14:15 UTC by disrupted

Closes #12

2021-08-24 05:30 UTC, philipp94831 requested changes

2021-08-24 05:30 UTC, philipp94831 commented on backend/streams_explorer/api/routes/node.py
> +async def node_schema_versions(node_id: str):
please rename the method. Methods should usually start with a verb

2021-08-25 07:17 UTC, disrupted commented on backend/streams_explorer/api/routes/node.py
> +async def node_schema_versions(node_id: str):
I would normally agree, but none of our api endpoints follow that format.

2021-08-25 07:19 UTC, philipp94831 commented on backend/streams_explorer/api/routes/node.py
> +async def node_schema_versions(node_id: str):
That is not a good argument ;-)

2021-08-25 07:19 UTC, philipp94831 commented on backend/streams_explorer/api/routes/node.py
> +async def node_schema_versions(node_id: str):
Then we need to also reduce technical debt in the future and rename other methods as well

2021-08-25 07:29 UTC, disrupted commented on backend/streams_explorer/api/routes/node.py
> +async def node_schema_versions(node_id: str):
fair point :) I renamed the methods, the rest I am gonna do in a separate PR.

2021-08-25 13:45 UTC, jakob-ed commented on frontend/src/components/Details.css
> +.ant-descriptions-item-label {
This is a standard antd classname right? If so, I think the styling could leak and affect other components as well since it seems we're not using CSS modules. Could be and idea then to add an extra class to `<Menu.Item ... />` (I guess that's what is styled here) and make the selector here more specific.

2021-08-30 08:26 UTC, disrupted commented on frontend/src/components/Details.css
> +.ant-descriptions-item-label {
good point! I changed the CSS selector to use our custom class there.

2021-08-30 09:14 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/schemaregistry.py
> +            return {}
You could extract a method or maybe even use a decorator for this :)

2021-08-30 09:21 UTC, jakob-ed approved these changes

2021-08-30 13:34 UTC, disrupted commented on backend/streams_explorer/core/services/schemaregistry.py
> +            return {}
good idea, I added a decorator with the default return value

2021-08-30 15:57 UTC, VictorKuenstler approved these changes

2021-08-30 16:02 UTC, merged