Add Kafka client to support topic configs
bakdata/streams-explorer pull request #164
Opened 2021-08-30 15:59 UTC by disrupted

Closes #109

2021-09-02 05:59 UTC, philipp94831 requested changes

2021-09-02 05:59 UTC, philipp94831 commented on backend/streams_explorer/streams_explorer.py
> +            config = self.kafka.get_topic_config(node_id)
How often is this fetched?

2021-09-02 05:59 UTC, philipp94831 commented on backend/tests/test_streams_explorer.py
> +                NodeInfoListItem(
What about a test where you
1. add a different topic config that is not shown
2. change the displayed information so that this config is shown

2021-09-03 07:29 UTC, VictorKuenstler requested changes

2021-09-03 07:29 UTC, VictorKuenstler commented on backend/streams_explorer/core/config.py
> +        Validator("kafka.config", must_exist=True, is_type_of=dict),
I think `bootstrap.servers` should be required in `kafka.config`

2021-09-03 07:29 UTC, VictorKuenstler commented on backend/settings.yaml
> +kafka:
What do you think about making this optional? I think this could make experimenting with the Streams Explorer easier for new users.

2021-09-03 07:29 UTC, VictorKuenstler commented on backend/streams_explorer/streams_explorer.py
> +        elif node_type == NodeTypesEnum.TOPIC or node_type == NodeTypesEnum.ERROR_TOPIC:
We could introduce a cache here maybe even for the whole node info endpoint. What do you think?

2021-09-06 09:45 UTC, disrupted commented on backend/streams_explorer/streams_explorer.py
> +        elif node_type == NodeTypesEnum.TOPIC or node_type == NodeTypesEnum.ERROR_TOPIC:
I agree, caching the whole node info endpoint would make sense. I am going to add it in a follow-up PR.

2021-09-06 09:48 UTC, disrupted commented on backend/settings.yaml
> +kafka:
I have made it an optional integration now (defaults to disabled)

2021-09-06 10:13 UTC, disrupted commented on backend/tests/test_streams_explorer.py
> +                NodeInfoListItem(
I've added a new test case in `test_node_info_extractor` for it now

2021-09-06 10:17 UTC, disrupted commented on backend/streams_explorer/streams_explorer.py
> +            config = self.kafka.get_topic_config(node_id)
Currently each time a node is selected, but I am going to add caching for this as Victor proposed https://github.com/bakdata/streams-explorer/pull/164#discussion_r701654879. I have opened an issue for it #165 that I will address in a follow-up directly

2021-09-06 10:18 UTC, philipp94831 commented on backend/streams_explorer/streams_explorer.py
> +            config = self.kafka.get_topic_config(node_id)
As this introduces unnecessary load to Kafka, I do not want to have a release of streams-explorer before #165 is solved then

2021-09-06 10:21 UTC, disrupted commented on backend/streams_explorer/streams_explorer.py
> +            config = self.kafka.get_topic_config(node_id)
yes, understood!

2021-09-06 12:52 UTC, philipp94831 approved these changes

2021-09-06 13:44 UTC, merged