Next.js migration
bakdata/streams-explorer pull request #193
Opened 2021-11-16 10:14 UTC by disrupted

- Initial commit from Create Next App
- Update Next
- Automatic update of tsconfig
- Remove demo pages
- Add G6 component
- Create dprint config
- Organize
- Remove example data
- Remove demo dependencies
- Create catch-all entry
- Move over main application
- Disable SSR
- Install dependencies
- Proxy api requests to backend
- Import ant design css
- Remove React router
- Format with dprint
- Add node icons
- Comment out React router stuff
- Load some CSS
- Remove old CSS stuff
- Configure Next to minify with SWC
- Migrate React router to Next useRouter
- Use native middleware instead of next-http-proxy-middleware
- Set MenuItem keys & Fix restore focus node
- Fix initial window dimensions being undefined
- Check that window is defined before rendering app
- Enable next lint
- Init tests
- Use Typescript instead of Javascript
- Cosmetics
- Remove deprecated ReactDOM.findDOMNode
- Migrate to new component structure
- Organize
- Fix right-aligned menu items
- Optimise GraphVis
- Todo
- Organize tests
- Organize tests
- Refactor wait & waitForElement to waitFor
- Update testing-library
- WIP migrate test
- Fix fetch is not defined
- Fix test rendering graph
- Fix test node icons in search
- Fix typescript complaining about jest-dom/extend-expect
- Move in subdir
- Move over project files
- Rename old frontend to frontend-cra
- Move frontend-next files & add next lint

2021-11-17 10:18 UTC, VictorKuenstler requested changes

2021-11-17 10:18 UTC, VictorKuenstler commented on frontend/components/App.tsx
> +  // TODO: switch to Image component
Do you want do resolve this TODO in this PR?

2021-11-17 10:18 UTC, VictorKuenstler commented on frontend/components/App.tsx
>    function pushHistoryFocusNode(nodeId: string) {
Method could be renamed to pushRouteFocueNode

2021-11-17 10:18 UTC, VictorKuenstler commented on frontend/components/DetailsCard.tsx
> +    <div ref={ref} className={style.details}>
nice :)

2021-11-17 10:18 UTC, VictorKuenstler commented on frontend/package.json
> +    "start": "next start",
`next start` starts the server in production mode, right? To make it easier to differentiate we could rename the script from `start` to `prod`

2021-11-17 10:18 UTC, VictorKuenstler commented on frontend/package.json
> +    "whatwg-fetch": "^3.6.2"
Why do we need this?

2021-11-17 10:18 UTC, VictorKuenstler commented on frontend/styles/global.css
> +  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
I think the first font should be a font that is not operating systems dependent. Just to stay as consistent as possible :)

2021-11-17 10:20 UTC, disrupted commented on frontend/components/App.tsx
> +  // TODO: switch to Image component
I tried it already, but it messed up the layout (vertically center the image on line), so I would visit this at a later point. Also I believe the improvements of Next image are more significant for larger images

2021-11-17 10:29 UTC, VictorKuenstler requested changes
![image](https://user-images.githubusercontent.com/8337857/142183601-85928fc7-84cf-4a72-a1e9-4f95c44b17a9.png)
The space between the menu items is a little too large on my screen now.

2021-11-17 10:55 UTC, disrupted commented on frontend/styles/global.css
> +  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
I didn't want to change that part as it's been our previous default https://github.com/bakdata/streams-explorer/blob/main/frontend/src/index.css

Should we leave it as it is or do you have a suggestion?

2021-11-17 10:56 UTC, disrupted commented on frontend/package.json
> +    "whatwg-fetch": "^3.6.2"
this is used for polyfilling some browser APIs (fetch) that are otherwise not available to Jest.

2021-11-17 10:57 UTC, disrupted commented on frontend/package.json
> +    "start": "next start",
makes sense, I changed it :)

2021-11-17 10:59 UTC, disrupted commented
> ![image](https://user-images.githubusercontent.com/8337857/142183601-85928fc7-84cf-4a72-a1e9-4f95c44b17a9.png)
> The space between the menu items is a little too large on my screen now.

Do you use an ultrawide monitor? I've pushed a fix, but could only repro/verify it when resizing the window to gigantic sizes

2021-11-17 12:19 UTC, VictorKuenstler commented
> > ![image](https://user-images.githubusercontent.com/8337857/142183601-85928fc7-84cf-4a72-a1e9-4f95c44b17a9.png)
> > The space between the menu items is a little too large on my screen now.
> 
> Do you use an ultrawide monitor? I've pushed a fix, but could only repro/verify it when resizing the window to gigantic sizes

Not ultrawide but QHD. It looks good now 👍

2021-11-22 08:56 UTC, VictorKuenstler commented on frontend/styles/global.css
> +  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
Ah ok, lets keep it then :)

2021-11-22 08:57 UTC, VictorKuenstler approved these changes

2021-11-22 09:09 UTC, merged