Resolve (extra) input topic patterns
bakdata/streams-explorer pull request #224
Opened 2022-03-04 14:45 UTC by VictorKuenstler

Fixes #215

2022-03-07 08:17 UTC, disrupted commented
will this only work for topics that are part of the internal topology? What about topics that are not connected to any other apps? From a user perspective, I think it would be very confusing if the resolved topics are incomplete.

2022-03-07 08:29 UTC, disrupted requested changes

2022-03-07 08:29 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            if DataFlowGraph.__get_node_topic(data) == NodeTypesEnum.TOPIC
I would find this easier to read and understand if it was `data.get("node_type") == NodeTypesEnum.TOPIC`

2022-03-07 08:29 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        ] = {}  # topic pattern -> list of target node ids
```suggestion
        ] = defaultdict(set)  # topic pattern -> list of target node ids
```

2022-03-07 08:29 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        node_ids = self._topic_pattern_queue.get(pattern, set())
you can use the defaultdict instead here

2022-03-07 08:34 UTC, philipp94831 requested changes

2022-03-07 08:34 UTC, philipp94831 commented on backend/streams_explorer/core/config.py
> +            "graph.resolve.input_pattern_topics.all", must_exist=True, is_type_of=bool
new lines, trailing comma

2022-03-07 08:34 UTC, philipp94831 commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            rx = re.compile(pattern=pattern)
regex would be a better name for the variable

2022-03-07 08:34 UTC, philipp94831 commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        self, matched_topic: str, node_id: str, pattern: str
trailing comma?

2022-03-07 08:34 UTC, philipp94831 commented on backend/tests/test_dataflow_graph.py
> +                    extra={
why is this part of a dict param? Wouldn't it make more sense to have a param `extra_input_patterns`?

2022-03-07 08:50 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +    def _get_topic_node_ids(graph: nx.DiGraph) -> List[str]:
please return a set
how about a shorter name like "filter_topics"
or "_filter_nodes" and pass in the filter condition as an argument?

2022-03-07 08:52 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        self, matched_topic: str, node_id: str, pattern: str
this is handled by the formatter (Black)

2022-03-14 15:10 UTC, VictorKuenstler commented on backend/tests/test_dataflow_graph.py
> +                    extra={
Good point, I added an extra param

2022-03-14 15:14 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +    def _get_topic_node_ids(graph: nx.DiGraph) -> List[str]:
I think `_filter_topic_node_ids` is more describing because, for `_filter_topics`, I would expect a list of some topic objects and not ids. The condition itself was the reason I extracted a method.

2022-03-14 15:17 UTC, VictorKuenstler commented
> will this only work for topics that are part of the internal topology? What about topics that are not connected to any other apps? From a user perspective, I think it would be very confusing if the resolved topics are incomplete.

Yes, it will only work for topics that are defined in the apps and connector configurations. I added support, so additionally, if `kafka.enable` is set to true, the topics that do not appear in configurations but exist in Kafka will be added as well.

2022-03-14 15:43 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            regex = re.compile(pattern=pattern)
the keyword argument is a little verbose/redundant here. just make it a positional argument

2022-03-14 15:45 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            return self.graph.nodes[id].get(NodeDataFields.NODE_TYPE)
are there any cases where `node_type` would be None?

2022-03-14 15:47 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            return self.graph.nodes[id].get(NodeDataFields.NODE_TYPE)
I don't think so

2022-03-14 15:49 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        return set(
please use Python's set comprehension here (`{ ... }` instead of `set([ ... ])`)

2022-03-14 15:57 UTC, disrupted commented on backend/streams_explorer/core/services/kafka_admin_client.py
> +        s = set(self._client.list_topics().topics.keys())
please inline :)

2022-03-14 16:08 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            },
if those two attributes are always used together, it might be better to define a namedtuple for it

```py
NodeData = namedtuple("NodeData", [NodeDataFields.NODE_TYPE, NodeDataFields.LABEL])

# usage
*NodeData(topic_name, NodeTypesEnum.ERROR_TOPIC),
```

2022-03-14 16:51 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            },
Good idea, but I think namedtuples do not support keyword unpacking. I thought about adding dataclasses or even a pedantic model. But this would introduce some overhead, so I think for the future, we could think about storing the data in the nodes differently and add a separate serializer for our use case.

2022-03-14 17:14 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            },
are you sure it doesn't work? I just tried it in ipython and it does work:

```py
from collections import namedtuple

T = namedtuple("T", ["a", "b"])

t = T(1, 2)


def foo(a, b):
    print(a)
    print(b)


foo(*t)
```

2022-03-14 17:17 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            },
sorry, misunderstanding. I didn't read the keyword argument part. My example is using positional args

2022-03-14 17:21 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            },
This results in positional arguments. For `add_topic` keyword arguments are required.

2022-03-14 17:25 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            },
Ah sorry, it just updated the conversion. Yep, unfortunately, we have to use keyword arguments here :)

2022-03-14 17:42 UTC, disrupted commented
one of the tests seems to be stuck/doesn't finish (CI runs until timeout) 🤔

2022-03-15 08:03 UTC, philipp94831 requested changes

2022-03-15 08:03 UTC, philipp94831 commented on backend/tests/test_dataflow_graph.py
> +        assert df.graph.has_edge("another-dead-letter-topic", "test-app2")
you should also check for the edged from fake2-dead-letter-topic

2022-03-15 08:12 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        for pattern, node_ids in self._topic_pattern_queue.items():
Yep, I reduced also the redundancy now

2022-03-15 08:26 UTC, philipp94831 requested changes

2022-03-15 08:26 UTC, philipp94831 commented on backend/streams_explorer/core/services/dataflow_graph.py
> +                    add_topic=True,
shouldn't this be false?

2022-03-15 08:26 UTC, philipp94831 commented on backend/streams_explorer/core/services/dataflow_graph.py
> +                    add_topic=True,
Also there should be a breaking test now

2022-03-15 08:31 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/dataflow_graph.py
> +                    add_topic=True,
Ah yes, good catch, thanks :) . It will not break because only the node attributes will be updated if we add a topic again. But since we only have two attributes for topics, the label and the node_type, there is no difference in the graph. I just added this, so we do not have to think about this part here if we might add some more attributes in the future.

2022-03-16 08:12 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        )  # topic pattern -> list of target node ids
sorry about nitpick :D
```suggestion
        )  # topic pattern -> set of target node ids
```

2022-03-16 08:13 UTC, disrupted approved these changes
LGTM

2022-03-16 08:14 UTC, philipp94831 commented on backend/streams_explorer/core/services/dataflow_graph.py
> +        )  # topic pattern -> list of target node ids
Never be sorry for being nitpicky in reviews ;-)

2022-03-17 07:48 UTC, merged