Update dependencies of demo pipeline
bakdata/streams-explorer pull request #250
Opened 2022-09-09 08:18 UTC by VictorKuenstler

2022-09-22 15:47 UTC, philipp94831 requested changes

2022-09-22 15:47 UTC, philipp94831 commented on demo-atm-fraud/build.gradle.kts
>      implementation(group = "com.bakdata.kafka", name = "error-handling", version = "1.0.0")
while you are at it: please use error-handling-avro 1.3.0

2022-09-22 15:47 UTC, philipp94831 commented on demo-atm-fraud/gradle.properties
> +confluentVersion=7.2.1
Are there topology tests? I recently had a problem with 7.2.1 because streams-bootstrap and fluent kafka are build using 7.2.0

2022-09-23 07:04 UTC, VictorKuenstler commented on demo-atm-fraud/gradle.properties
> +confluentVersion=7.2.1
Yes there are topology tests. But I will change it to `7.2.0`

2022-09-23 07:05 UTC, philipp94831 commented on demo-atm-fraud/gradle.properties
> +confluentVersion=7.2.1
I mean if it works, it is fine

2022-09-23 07:08 UTC, philipp94831 commented on demo-atm-fraud/build.gradle.kts
> +    implementation(group = "com.bakdata.kafka", name = "error-handling", version = "1.3.0")
the module is error-handling-avro. There are also some minor code changes to make, you need use AvroDeadLetterConverter and transformaValues

2022-09-23 07:14 UTC, VictorKuenstler commented on demo-atm-fraud/build.gradle.kts
> +    implementation(group = "com.bakdata.kafka", name = "error-handling", version = "1.3.0")
Ah thanks, I changed it.

2022-09-23 07:16 UTC, philipp94831 approved these changes

2022-09-23 07:18 UTC, merged