Fix JDBC & S3 sinks not being cleared upon refresh
bakdata/streams-explorer pull request #255
Opened 2022-09-21 13:00 UTC by disrupted

2022-09-26 15:07 UTC, philipp94831 requested changes

2022-09-26 15:07 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/extractor.py
> +class CronJobExtractor(Extractor):
In order to name it similarly to StreamsAppExtractor, I would rather call it ProducerAppExtractor

2022-09-26 15:07 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/extractor_container.py
> +            if isinstance(extractor, ConnectorExtractor):
For now this is fine but we should move away from using isinstance checks. The best ways to handle this is using proper interfaces where we call methods on or use the visitor pattern

2022-09-26 15:07 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/extractor_container.py
> +            if isinstance(extractor, ConnectorExtractor):
This is what caused the bug with S3 sink and JDBC, right? I don't see a test that covers this

2022-09-27 06:53 UTC, VictorKuenstler requested changes

2022-09-27 06:53 UTC, VictorKuenstler commented on backend/streams_explorer/plugins.py
> +            (name, val) for name, val in members if val.__module__ == module.__name__
You could use filter here

2022-09-27 07:24 UTC, disrupted commented on backend/streams_explorer/plugins.py
> +            (name, val) for name, val in members if val.__module__ == module.__name__
that's true, however the use of a simple list comprehension is preferred over `filter` (or `map`) as these are older and often less concise.

I find the list comprehension far easier to read than
```python
members = filter(
    lambda member: member[1].__module__ == module.__name__, members
)
```

2022-09-27 07:28 UTC, disrupted commented on backend/streams_explorer/core/extractor/extractor_container.py
> +            if isinstance(extractor, ConnectorExtractor):
I agree, thanks for the suggestion about visitor pattern! I will look into it for a further improvement.

2022-09-27 14:18 UTC, disrupted commented on backend/streams_explorer/core/extractor/extractor_container.py
> +            if isinstance(extractor, ConnectorExtractor):
I have added a test now

2022-09-27 15:48 UTC, philipp94831 approved these changes

2022-09-28 06:54 UTC, merged