Feat/update demo screen
bakdata/streams-explorer pull request #268
Opened 2022-11-02 09:48 UTC by MichaelKora

Since the demo pipeline was updated, i just also updated the screenshot so it matches to the current pipeline.

2022-11-02 10:00 UTC, raminqaf commented on settings.gradle
> +rootProject.name = 'streams-explorer'
The `streams-explorer` is not a Java project

2022-11-02 10:02 UTC, raminqaf requested changes

2022-11-02 10:02 UTC, raminqaf commented on gradlew.bat
> +@rem
Remove

2022-11-02 10:03 UTC, yannick-roeder commented on build.gradle
> +/*
We don't need Gradle in this project. Please remove this file and all other Gradle files

2022-11-02 10:05 UTC, disrupted commented
thanks for the new screenshot! you can overwrite the previous `screens/demo-pipeline.png` directly

2022-11-02 10:19 UTC, MichaelKora commented on .gitignore
> +# Ignore Gradle build output directory
you mean the comments?

2022-11-02 10:20 UTC, MichaelKora commented on gradlew
> +#!/bin/sh
i actually have only changed the README file.

2022-11-02 12:16 UTC, disrupted commented on .gitattributes
> +#
what do we need this file for?

2022-11-02 12:20 UTC, disrupted commented on demo-atm-fraud/README.md
> -
(unrelated to this PR) this is not necessary anymore thanks to your new transaction producer, right? If we don't need it anymore, we should remove or edit this section imo

2022-11-02 12:21 UTC, disrupted commented on demo-atm-fraud/README.md
> -
feel free to do it in a followup PR :)

2022-11-02 12:23 UTC, raminqaf commented on .gitignore
> +mock/
newline :D

2022-11-02 12:30 UTC, MichaelKora commented on .gitattributes
> +#
we dont need it at all. it was auto generated

2022-11-02 12:34 UTC, MichaelKora commented on demo-atm-fraud/README.md
> -
will do

2022-11-02 16:38 UTC, yannick-roeder commented on .gitignore
> +mock/
This is not resolved yet, please add a new line at the end of the file

2022-11-02 16:39 UTC, yannick-roeder commented on .gitattributes
> +#
This is not resolved yet, please remove this file from the MR

2022-11-03 08:42 UTC, raminqaf approved these changes

2022-11-03 08:47 UTC, disrupted approved these changes

2022-11-03 10:19 UTC, yannick-roeder approved these changes

2022-11-04 10:23 UTC, merged