Create plugin for Redis sink connector
bakdata/streams-explorer pull request #291
Opened 2023-02-15 12:23 UTC by disrupted

Closes #288

2023-02-15 16:24 UTC, MichaelKora submitted a review, later dismissed

2023-02-15 17:09 UTC, disrupted commented
I found that when using multiple input topics, the naming is inconsistent for the sink. will have to revert it back to using the Redis host name instead of input topic name for the database sink

2023-02-16 09:00 UTC, philipp94831 requested changes

2023-02-16 09:00 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/default/redis_sink.py
> +                type=KafkaConnectorTypesEnum.SINK,
shouldn't this be part of the class itself?

2023-02-16 09:00 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/default/redis_sink.py
> +                error_topic=None,
Shouldn't this be set in the same way as for ES sink?

2023-02-16 09:11 UTC, disrupted commented on backend/streams_explorer/core/extractor/default/redis_sink.py
> +                type=KafkaConnectorTypesEnum.SINK,
yes, that's right https://github.com/bakdata/streams-explorer/issues/223

2023-02-16 09:14 UTC, disrupted commented on backend/streams_explorer/core/extractor/default/redis_sink.py
> +                error_topic=None,
yeah, I think we can remove this argument as it's the default anyways and rely on the default implementation to scan for `errors.deadletterqueue.topic.name`. is that what you mean?

2023-02-16 09:22 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/default/redis_sink.py
> +                type=KafkaConnectorTypesEnum.SINK,
But can't you set it in the init method of RedisSinkConnector?

2023-02-16 09:25 UTC, disrupted commented on backend/streams_explorer/core/extractor/default/redis_sink.py
> +                type=KafkaConnectorTypesEnum.SINK,
good point!

2023-02-16 09:36 UTC, philipp94831 approved these changes

2023-02-16 10:03 UTC, merged