Build Multi-Platform Docker Image
bakdata/streams-explorer pull request #306
Opened 2024-06-21 10:18 UTC by yordanovsstoyan

2024-06-24 06:58 UTC, disrupted commented on frontend/package.json
> +    "dprint": "0.39.1",
why not keep the `^`?

2024-06-24 06:58 UTC, disrupted commented on Dockerfile
> +CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
please fix EOF (missing newline)

2024-06-24 06:58 UTC, disrupted commented on .github/workflows/ci.yml
> +          platforms: linux/amd64,linux/arm64
great! 😍

2024-06-24 07:27 UTC, JakobEdding commented on Dockerfile
> +    apt-get -y install gcc build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
@disrupted do you think we could avoid installing system libs by updating some Python deps to versions for which wheels are available for ARM?

2024-06-24 07:42 UTC, JakobEdding requested changes

2024-06-24 07:42 UTC, JakobEdding commented on backend/mypy.ini
> +exclude = ['env/']
For me, mypy runs through by getting rid of this file, removing the `--config-file` flag in run_mypy.sh and appending `exclude = ['.venv/']` to the mypy section in setup.cfg. I think we should simplify the config this way.

2024-06-24 08:29 UTC, yordanovsstoyan commented on Dockerfile
> +    apt-get -y install gcc build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
Probably yes

2024-06-24 08:49 UTC, JakobEdding commented on Dockerfile
> +    apt-get -y install gcc build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
I took a look and it doesn't seem possible atm. @yordanovsstoyan, can you add a comment here linking to this issue? https://github.com/Automattic/node-canvas/issues/1662

2024-06-24 11:43 UTC, JakobEdding commented on backend/mypy.ini
> +exclude = ['env/']
It should be fine to remove this file now

2024-06-24 13:47 UTC, disrupted commented on frontend/package.json
> +    "dprint": "0.39.1",
unresolving because I don't see this changed

2024-06-25 05:40 UTC, yordanovsstoyan commented on frontend/package.json
> +    "dprint": "0.39.1",
Sorry, idk why my change locally was not pushed

2024-06-25 09:51 UTC, disrupted approved these changes

2024-06-25 10:02 UTC, merged