Update graph automatically
bakdata/streams-explorer pull request #36
Opened 2021-02-03 14:19 UTC by VictorKuenstler

Closes #33

2021-02-03 15:16 UTC, philipp94831 commented on backend/requirements.txt
> +fastapi-utils==0.2.1
isn't there a lock file or sth that is update everytime? Also the new lines are unnecessary but not too important ;-)

2021-02-03 15:16 UTC, philipp94831 reviewed
What about a test?

2021-02-03 15:17 UTC, disrupted commented on backend/requirements.txt
> +fastapi-utils==0.2.1
luckily not for Python :)

2021-02-03 15:26 UTC, disrupted requested changes

2021-02-03 15:26 UTC, disrupted commented on backend/settings.yaml
> +# update graph (fetch deployments and connectors) every X seconds
Can you add this to the Readme?

2021-02-03 16:00 UTC, disrupted approved these changes
LGTM

2021-02-03 17:23 UTC, VictorKuenstler commented
> What about a test?

I added a test that should cover this.

2021-02-04 09:05 UTC, philipp94831 approved these changes

2021-02-04 09:35 UTC, merged