Add extractors for Amazon S3 & JDBC sink connectors
bakdata/streams-explorer pull request #38
Opened 2021-02-03 14:30 UTC by disrupted

Closes #29 #30 #45

2021-02-08 17:57 UTC, philipp94831 requested changes

2021-02-08 17:57 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/default/jdbc_sink.py
> +                        name=name,
`table.name.format`, maybe even in combination with `connection.url`

2021-02-08 17:57 UTC, philipp94831 commented on frontend/public/jdbc-sink.svg
> +<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-database" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="rou
Did you check the license?

2021-02-09 09:33 UTC, disrupted commented on frontend/public/jdbc-sink.svg
> +<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-database" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="rou
Yes, it's the same source as our other glyphs, https://github.com/tabler/tabler-icons, all MIT licensed

2021-02-09 09:35 UTC, philipp94831 commented on frontend/public/jdbc-sink.svg
> +<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-database" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="rou
Then we probably should add the license to the folder
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

https://github.com/tabler/tabler-icons/blob/master/LICENSE

2021-02-09 09:45 UTC, disrupted commented on backend/streams_explorer/core/extractor/default/jdbc_sink.py
> +                        name=name,
Added `table.name.format`

2021-02-09 10:56 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/default/jdbc_sink.py
> +                        name=name,
Don't know if this is possible but what about adding the connection.url to the node detailts?

2021-02-09 11:02 UTC, VictorKuenstler commented on backend/streams_explorer/core/extractor/default/jdbc_sink.py
> +                        name=name,
I think this can be configured using the `kafkaconnect.displayed_information` setting.

2021-02-09 11:03 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/default/jdbc_sink.py
> +                        name=name,
I am talking about the DB node, not the connector node

2021-02-09 11:10 UTC, VictorKuenstler commented on backend/streams_explorer/core/extractor/default/jdbc_sink.py
> +                        name=name,
Ah, my bad, adding node info items to sink/source nodes is not possible at the moment.

2021-02-09 11:11 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/default/jdbc_sink.py
> +                        name=name,
Ok, added #54

2021-02-09 11:11 UTC, philipp94831 approved these changes

2021-02-09 11:19 UTC, merged