Link to consumer groups Grafana dashboard
bakdata/streams-explorer pull request #41
Opened 2021-02-03 16:48 UTC by disrupted

Closes #37

2021-02-04 09:03 UTC, philipp94831 requested changes
What about connectors?

2021-02-04 09:50 UTC, disrupted commented
Added connectors and also a better test that mocks the consumer group annotation.

2021-02-04 11:58 UTC, philipp94831 commented on backend/streams_explorer/defaultlinker.py
> +            NodeInfoListItem(
Can't you reuse the same NodeInfoListItem from streaming_app_info?

2021-02-04 13:06 UTC, disrupted commented on backend/streams_explorer/defaultlinker.py
> +            NodeInfoListItem(
I can change it of course. imo it looks a little less structured and readable though, what do you think?
```python
grafana_consumer_link = NodeInfoListItem(
    name="Consumer Group Monitoring", value="grafana", type=NodeInfoType.LINK
)
self.topic_info = [
    NodeInfoListItem(
        name="Topic Monitoring", value="grafana", type=NodeInfoType.LINK
    ),
    NodeInfoListItem(
        name="Message Viewer", value="akhq", type=NodeInfoType.LINK
    ),
]
self.streaming_app_info = [
    grafana_consumer_link,
    NodeInfoListItem(
        name="Kibana Logs", value="kibanalogs", type=NodeInfoType.LINK
    ),
]
self.connector_info = [grafana_consumer_link]
self.sink_source_info = {
    "elasticsearch-index": [
        NodeInfoListItem(name="Kibana", value="", type=NodeInfoType.LINK)
    ]
}
```

2021-02-08 08:55 UTC, philipp94831 approved these changes

2021-02-08 09:37 UTC, merged