Fix node_type KeyError
bakdata/streams-explorer pull request #43
Opened 2021-02-03 17:04 UTC by disrupted

2021-02-03 17:22 UTC, philipp94831 requested changes
Please add a test

2021-02-04 09:05 UTC, philipp94831 commented
Is this fix now correct or did @VictorKuenstler identify the issue with #36?

2021-02-04 10:03 UTC, VictorKuenstler commented
> Is this fix now correct or did @VictorKuenstler identify the issue with #36?

I think #36 should fix this. But I would observe whether we experience it again and keep this open for now.

2021-02-08 15:46 UTC, philipp94831 approved these changes

2021-02-08 15:46 UTC, VictorKuenstler approved these changes

2021-02-08 15:51 UTC, merged