Add support for source connectors
bakdata/streams-explorer pull request #58
Opened 2021-02-10 15:18 UTC by disrupted

2021-02-10 15:37 UTC, philipp94831 requested changes

2021-02-10 15:37 UTC, philipp94831 commented on backend/streams_explorer/core/services/kafkaconnect.py
> +            topics = config.get("transforms.changeTopic.replacement")
Can the connector decide this? Because different source connectors might work differently and it is only needed for our one source connector

2021-02-10 15:37 UTC, philipp94831 commented on backend/streams_explorer/core/services/kafkaconnect.py
> +        return KafkaConnect.get_topics(topics), config, type
I know it has been like this before but it should return a proper object

2021-02-11 16:47 UTC, philipp94831 requested changes

2021-02-11 16:47 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/extractor.py
> +            return topics.replace(" ", "").split(",")
I think it is more clear if you do split first and then strip()

2021-02-11 16:47 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/extractor_container.py
> +                return topics
You iterate but return inside the loop? Is that intentionally?

2021-02-11 16:47 UTC, philipp94831 commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            if connector.type == KafkaConnectorTypesEnum.SOURCE:
Please add a test for sources

2021-02-11 16:50 UTC, disrupted commented on backend/streams_explorer/core/extractor/extractor.py
> +            return topics.replace(" ", "").split(",")
Alright I can change it, although this approach seems a bit more robust to me. Something like this can't happen, right? `"topic-1, topic-2, "` Because then we would end up with an empty string in the topics list

2021-02-11 16:51 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/extractor.py
> +            return topics.replace(" ", "").split(",")
Fair point, keep it like this

2021-02-11 16:54 UTC, disrupted commented on backend/streams_explorer/core/extractor/extractor_container.py
> +                return topics
I am not sure if one connector can have multiple extractors. If so I would need to change it and probably return a Set instead of List for topics to avoid possible duplicates.
The way it is now it stops iterating over the extractor plugins after a match.

2021-02-11 16:59 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/extractor_container.py
> +                return topics
Sounds reasonable

2021-02-11 17:24 UTC, disrupted commented on backend/streams_explorer/core/services/dataflow_graph.py
> +            if connector.type == KafkaConnectorTypesEnum.SOURCE:
Added

2021-02-11 17:25 UTC, philipp94831 approved these changes

2021-02-11 17:35 UTC, merged