Connector dead letter topic
bakdata/streams-explorer pull request #59
Opened 2021-02-15 11:45 UTC by disrupted

2021-02-15 15:16 UTC, philipp94831 requested changes

2021-02-15 15:16 UTC, philipp94831 commented on backend/streams_explorer/core/services/kafkaconnect.py
> +                    topics=[],
If it is a sink, we can always read the topics field https://docs.confluent.io/platform/current/installation/configuration/connect/sink-connect-configs.html#sinkconnectorconfigs_topics Same is true for error topics

2021-02-15 15:16 UTC, philipp94831 commented on backend/streams_explorer/core/services/kafkaconnect.py
> +            # if no specific connector is returned create generic one
What about a test?

2021-02-15 17:43 UTC, disrupted commented on backend/streams_explorer/core/services/kafkaconnect.py
> +                    topics=[],
Added new generic extractors for sink & source connectors as fallback. I think this way it is cleaner than putting the sink connector specific parsing in this method.

2021-02-15 17:44 UTC, disrupted commented on backend/streams_explorer/core/services/kafkaconnect.py
> +            # if no specific connector is returned create generic one
Yes good point, I am gonna add some tests for the new extractors.

2021-02-16 16:32 UTC, philipp94831 approved these changes

2021-02-16 16:36 UTC, merged