Add support for cronjob extractor application nodes
bakdata/streams-explorer pull request #72
Opened 2021-02-24 17:59 UTC by disrupted

2021-02-25 11:53 UTC, philipp94831 requested changes
What about a test?

2021-02-25 11:58 UTC, disrupted commented
> What about a test?

it's included in the extractor plugin

2021-02-25 11:59 UTC, philipp94831 commented
> > What about a test?
> 
> it's included in the extractor plugin

But there should be one here as well

2021-02-25 12:08 UTC, disrupted commented
> But there should be one here as well

hm I think it's already covered. What do you think I should test here?

2021-02-25 12:10 UTC, philipp94831 commented
> > But there should be one here as well
> 
> hm I think it's already covered. What do you think I should test here?

That an application is created from a cronjob

2021-02-25 14:31 UTC, philipp94831 commented on backend/streams_explorer/core/extractor/extractor_container.py
> +    def on_cron_job(self, cron_job: V1beta1CronJob) -> Optional[V1Deployment]:
Shouldn't this be K8sApp instead of V1Deployment?

2021-02-25 14:34 UTC, disrupted commented on backend/streams_explorer/core/extractor/extractor_container.py
> +    def on_cron_job(self, cron_job: V1beta1CronJob) -> Optional[V1Deployment]:
WIP, let me mark this as a Draft again

2021-02-25 17:21 UTC, philipp94831 reviewed
Are you able to do the thing with the active edges now by checking for K8sAppCronJob and marking all incoming edges just as the outgoing edge?

2021-03-01 09:38 UTC, philipp94831 approved these changes

2021-03-01 09:39 UTC, merged