Ingress object in helm chart should support ingress class spec
bakdata/streams-explorer pull request #87
Opened 2021-04-23 14:45 UTC by twiechert

adding optional value ingressClassName to be used in more recent k8 versions

2021-04-26 10:02 UTC, VictorKuenstler commented
Hello @twiechert, please package the chart using `helm package .` in the `helm-chart` directory.

2021-04-26 14:05 UTC, twiechert commented
Oh yes, thanks for the hint.

I took the freedom to another optional field commonly used (imagePullSecrets).

Also, I wasn't sure about the chart versioning flow applied here, but from my understanding, it would otherwise override the current 0.1.0 (upon helm repo update), thus I bumped the minor version.

2021-04-26 16:17 UTC, VictorKuenstler commented
> Oh yes, thanks for the hint.
> 
> I took the freedom to another optional field commonly used (imagePullSecrets).
> 
> Also, I wasn't sure about the chart versioning flow applied here, but from my understanding, it would otherwise override the current 0.1.0 (upon helm repo update), thus I bumped the minor version.

We version the chart by releasing a new tag after merging it into master. But bumping the version additionally is fine.

Somehow, the diff includes the diff of https://github.com/bakdata/streams-explorer/pull/89, could you please check?

2021-04-27 17:03 UTC, twiechert commented
hey @VictorKuenstler,

I actually rebased the MR, I'm not sure why the diff view indicates the changes twice - but that should be taken by the squash option in any case, or?

2021-04-28 08:44 UTC, VictorKuenstler requested changes

2021-04-28 08:44 UTC, VictorKuenstler commented on helm-chart/templates/ingress.yaml
> +  ingressClassName: {{.Values.ingress.ingressClassName}}
Please add an example for the `ingressClassName` in the `values.yaml` as a comment.

2021-04-28 09:46 UTC, VictorKuenstler commented on helm-chart/values.yaml
> +  # Commonly used to map ingres objects to specific ingress controller installations within your cluster
Minor, but there is a typo for ingress.

2021-04-28 09:54 UTC, VictorKuenstler approved these changes
LGTM, thanks for your contribution @twiechert!

2021-04-28 09:54 UTC, twiechert commented
one more side remark:

based on the rebuilt I deleted the old helm chart.

I wonder if it might be more appropriate to retain the old chart artifacts in the master.

reason being:
our vendir based pipeline failed syncing our vendor charts, since a new streams explorer helm chart had been releases and the previous one being referenced was no longer accessible through the master branch.

2021-04-28 09:56 UTC, philipp94831 commented
> one more side remark:
> 
> based on the rebuilt I deleted the old helm chart.
> 
> I wonder if it might be more appropriate to retain the old chart artifacts in the master.
> 
> reason being:
> our vendir based pipeline failed syncing our vendor charts, since a new streams explorer helm chart had been releases and the previous one being referenced was no longer accessible through the master branch.

You can always reference tags or commits instead of master branch when adding the repo. In the future, we will hopefully release the chart to a proper helm chart repo and this should no longer be an issue

2021-04-28 09:57 UTC, twiechert commented
yep this is what we have done now, but I agree a proper chart repo will be the go-to solution anyways.

2021-04-28 11:04 UTC, merged