Decouple PrometheusMetricProvider from specific metric names
bakdata/streams-explorer pull request #92
Opened 2021-04-27 19:02 UTC by twiechert

This is an implementation for https://github.com/bakdata/streams-explorer/issues/91 and decouples the PrometheusMetricProvider from specific metric names.

Alternative, but also Prometheus-based implementations can reuse the provided functionality.

2021-04-30 14:40 UTC, VictorKuenstler commented
Hi @twiechert, to better understand the motivation behind these changes, could you please give an example of how other Prometheus-based implementations would utilize the changes you made?

2021-04-30 15:01 UTC, twiechert commented
In our case we are overriding all metrics because we use different exporters, but consider the case, you only need to overwrite one (e.g. the connect one).


```python

# no need to override the bundled one, I could provide an implementation for all metrics, then I would simply write (PrometheusMetricInterface)
class CustomPrometheusMetrics(BundledPrometheusMetrics):

    def get_consumer_read_rate_metric_query(self) -> str:
        return "sum by(topic) (my_very_own_metric)"

    # others are fine or I provide all others myself as well

class CustomPrometheusMetricProvider(PrometheusMetricProvider):

    def __init__(self, nodes: NodeDataView):
        super().__init__(nodes, CustomPrometheusMetrics())
```

2021-05-04 09:22 UTC, VictorKuenstler requested changes

2021-05-04 09:22 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/metric_providers.py
> +class BundledPrometheusMetrics(PrometheusMetricInterface, DanielqsjKafkaExporterMetrics, KafkaLagExporterMetrics):
I tested it in our cluster, and it currently fails when pulling the Prometheus metrics. It returns `None` for the queries such as `get_messages_out_metric_query`. Could you please add a test to ensure that the correct queries are returned for the `BundledPrometheusMetrics`class? 

I think `PrometheusMetricInterface` could also be an ABC so that the `BundledPrometheusMetrics` overrides all abstract (query) methods. The methods could call static methods of `KafkaLagExporterMetrics ` and `DanielqsjKafkaExporterMetrics `. This way, one could also override some of the queries of `BundledPrometheusMetrics` easily. What do you think?

2021-05-05 06:43 UTC, twiechert commented on backend/streams_explorer/core/services/metric_providers.py
> +class BundledPrometheusMetrics(PrometheusMetricInterface, DanielqsjKafkaExporterMetrics, KafkaLagExporterMetrics):
Hi @VictorKuenstler, from my understanding  PrometheusMetricInterface is already an ABC, at least conceptually, or are you suggesting to add _@abstractmethod_  decorators (sorry am not really a python developer)?

I will in any case revisit the MR functionally check functionality through some tests at the latest this weekend.

2021-05-05 07:16 UTC, VictorKuenstler commented on backend/streams_explorer/core/services/metric_providers.py
> +class BundledPrometheusMetrics(PrometheusMetricInterface, DanielqsjKafkaExporterMetrics, KafkaLagExporterMetrics):
Hi @twiechert, yes, exactly. I mean the `@abstractmethod` decorators so that those methods are required to be implemented.

2021-07-20 07:52 UTC, disrupted commented
Hey @twiechert,
I wanted to let you know that I recently did a refactoring of the Prometheus metric provider. It is now decoupled from the specific Prometheus queries which are now only part of the `PrometheusMetric` enum. https://github.com/bakdata/streams-explorer/pull/137
Does this perhaps solve your issue?

2021-07-26 11:20 UTC, twiechert commented
@disrupted this sounds great - sorry for not coming back to you with the requested changes. I relocated and then forgot this topic.

2021-07-26 11:20 UTC, closed without merging